import productImage1 from "src/assets/images/product1.png";
import productImage2 from "src/assets/images/product2.png";
import productImage3 from "src/assets/images/product3.png";
import productImage4 from "src/assets/images/product4.png";
export const dataProduct = [
  {
    id: 1,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage1,
    categoryId: 1,
  },
  {
    id: 2,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage2,
    categoryId: 2,
  },
  {
    id: 3,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage3,
    categoryId: 1,
  },
  {
    id: 4,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage4,
    categoryId: 2,
  },
  {
    id: 5,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage1,
    categoryId: 2,
  },
  {
    id: 6,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage2,
    categoryId: 1,
  },
  {
    id: 7,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage3,
    categoryId: 1,
  },
  {
    id: 8,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage4,
    categoryId: 3,
  },
  {
    id: 9,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage1,
    categoryId: 3,
  },
  {
    id: 10,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage2,
    categoryId: 2,
  },
  {
    id: 11,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage1,
    categoryId: 2,
  },
  {
    id: 12,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage2,
    categoryId: 3,
  },
  {
    id: 13,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage3,
    categoryId: 4,
  },
  {
    id: 14,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage4,
    categoryId: 3,
  },
  {
    id: 15,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage1,
    categoryId: 1,
  },
  {
    id: 16,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage2,
    categoryId: 3,
  },
  {
    id: 17,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage3,
    categoryId: 5,
  },
  {
    id: 18,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage4,
    categoryId: 4,
  },
  {
    id: 19,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage1,
    categoryId: 5,
  },
  {
    id: 20,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage2,
    categoryId: 4,
  },
  {
    id: 21,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage1,
    categoryId: 4,
  },
  {
    id: 22,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage2,
    categoryId: 5,
  },
  {
    id: 23,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage3,
    categoryId: 4,
  },
  {
    id: 24,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage4,
    categoryId: 6,
  },
  {
    id: 25,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage1,
    categoryId: 5,
  },
  {
    id: 26,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage2,
    categoryId: 6,
  },
  {
    id: 27,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage3,
    categoryId: 5,
  },
  {
    id: 28,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage4,
    categoryId: 6,
  },
  {
    id: 29,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage1,
    categoryId: 7,
  },
  {
    id: 30,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage2,
    categoryId: 7,
  },
  {
    id: 31,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage1,
    categoryId: 6,
  },
  {
    id: 32,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage2,
    categoryId: 6,
  },
  {
    id: 33,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage3,
    categoryId: 7,
  },
  {
    id: 34,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage4,
    categoryId: 8,
  },
  {
    id: 35,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage1,
    categoryId: 7,
  },
  {
    id: 36,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage2,
    categoryId: 7,
  },
  {
    id: 37,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage3,
    categoryId: 8,
  },
  {
    id: 38,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage4,
    categoryId: 8,
  },
  {
    id: 39,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage1,
    categoryId: 8,
  },
  {
    id: 40,
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 299000,
    saleOff: 10,
    ammount: 20,
    category: "Lọc gió động cơ",
    image: productImage2,
    categoryId: 8,
  },
];
